use std::{
    env,
    fs::{self, File},
    path::Path,
};

use serde::Deserialize;

#[derive(Deserialize)]
struct InferenceConfig {
    #[serde(rename = "PostProcess")]
    post_process: PostProcessConfig,
}

#[derive(Deserialize)]
struct PostProcessConfig {
    character_dict: Vec<String>,
}

pub fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR was not set by Cargo. Aborting...");
    let out_path = Path::new(&out_dir);

    // Parse dictionary from inference.yml
    let yaml_path = "data/models/PP_OCRv6_tiny_rec_inference.yml";
    println!("cargo:rerun-if-changed={yaml_path}");
    let yaml_file = File::open(yaml_path).expect(&format!("Failed to open {:}", yaml_path));
    let infrence_config: InferenceConfig =
        serde_saphyr::from_reader(yaml_file).expect(&format!("Failed to parse {:}", yaml_path));

    // Convert yaml content into array declaration
    let n_characters = infrence_config.post_process.character_dict.len() + 2; // CTC blank and space
    let mut code_character_dict = String::with_capacity(n_characters * 8 + 150); // should roughly be enough
    code_character_dict
        .push_str("/// Autogenerated static character dictionary compiled from `inference.yml.\n");
    code_character_dict.push_str(&format!(
        "pub static CHARACTER_DICT: [char; {n_characters}] = [\n"
    ));
    code_character_dict.push_str("    \'_\',\n"); // CTC Blank (placeholder)
    for character in &infrence_config.post_process.character_dict {
        if character.chars().count() != 1 {
            panic!(
                "An entry in the inference character dict contained more than on character: {:}",
                character
            );
        }
        let actual_char: char = character.chars().next().unwrap();
        match actual_char {
            '\\' => {
                code_character_dict.push_str(&format!("    \'\\\\\',\n")); // Edge case: '\'
            }
            '\'' => {
                code_character_dict.push_str(&format!("    \'\\\'\',\n")); // Edge case: '\'
            }
            _ => {
                code_character_dict.push_str(&format!("    \'{actual_char}\',\n"));
            }
        }
    }
    code_character_dict.push_str("    \' \',\n"); // Space character
    code_character_dict.push_str("];\n");
    fs::write(out_path.join("dictionary.rs"), code_character_dict)
        .expect("Failed to write autogenerated dictionary.rs");
}
